version: "3"

services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    container_name: mongo-server
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db

  app:
    container_name: room-rent-server
    depends_on:
      - mongodb
    build: ./
    restart: unless-stopped
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./userDataUpload:/app/userDataUpload
